---
title: "Explore_data"
format: html
editor: visual
---

```{r Library}
#| label: setup
library(readxl)
library(tidyverse)
library(PxWebApiData)
library(writexl)
library(ggplot2)
library(tinytex)
library(ggpubr)
```

## Leser inn SSB Data

Data henta frå https://www.ssb.no/statbank/table/10540/ 04.05.2025

### Parameter:

-   Måned: 2014M01-2014M12
-   Region: Alle kommuner - Sandnes (-2019), Stavanger, Eigersund, Haugesund.
-   Alder: 15-29, 30-74

```{r Excel reader}
ssb10540 <- read_excel("./ssb10540.xlsx")
View(ssb10540)
```

```{r}
#| eval: false
  View(ssb10540)
```

```{r Header replacer}
names(ssb10540) <- c("knr", "alder", "mnd", "arbl")
```

```{r Filling empty cells}
ssb10540 <- fill(ssb10540, knr, alder, .direction = "down")
```

## Lagre data

```{r RData saver}
save(ssb10540,
     file = "My-first-regional-unemployment-table.RData")
rm(ssb10540)
```

```{r}
load(file = "My-first-regional-unemployment-table.RData")
```

```{r Writing to excel}
write_xlsx(
  x = ssb10540,
  path = "Prepared10540.xlsx",
  format_headers = TRUE,
  use_zip64 = FALSE
)
```

```{r Writing to csv}
write_csv(
  ssb10540,
  file = "ssb10540.csv"
)
```

## SSB API

```{r}
#| paged.print: false
ApiData(
  "https://data.ssb.no/api/v0/en/table/10540/",
  returnMetaFrames = TRUE
)
```

```{r}
#| paged.print: false
ApiData(
  "https://data.ssb.no/api/v0/en/table/10540/",
  returnApiQuery = TRUE
)
```

```{r}
unemp99to02 <- ApiData12(
  urlToData = "https://data.ssb.no/api/v0/en/table/10540/",
  # or
  # urlToData = "10540"
  # Select all municipalities in Vest-Agder and Rogaland
  Region = list(c("10*","11*")),
  # Select two age groups
  Alder = c("15-74", "15-29"),
  # select 1999M01:2002M12
  Tid = c(paste(
    rep(1999:2002, each = 12), 
    "M",
    sprintf("%02d", 1:12), 
    sep = "")
    )
  ) |> 
  # convert from dataframe to tibble
  as_tibble()
```

```{r}
# pick and order variables. 
unemp99to02 <- unemp99to02 |> 
  select(
    knr = Region, 
    kname = region,  
    month, 
    age, 
    unemp = value
    )
```

```{r}
# Check that it looks OK
head(unemp99to02, n = 5)
```

## GGplot

```{r}

```

```{r}
ggplot() +
  geom_point(data = mtcars,
             mapping = aes(x = disp, y = mpg, colour = factor(cyl), size = 3.6*(0.25*1609.347)/qsec,
                           shape = factor(ifelse(am, "Man", "Aut")))) +
  labs(colour = "cyl", size = "speed\n(km/h)", shape = "trans-\nmission")
```

```{r}
ggplot() +
  geom_point(
    data = mtcars,
    mapping = aes(
      x = disp,
      y = mpg, 
      colour = factor(cyl), 
      size = 3.6*(0.25*1609.347)/qsec, 
      shape = factor(
        # Note codeing am
        # 0 automatic, 1 manual
        ifelse(
          am, 
          "Aut", 
          "Man"
          )
        )
      )
    ) +
  labs(
    colour = "cyl", 
    size = "speed\n(km/h)", 
    shape = "trans-\nmission"
    ) +
  geom_smooth(
    data = mtcars, 
    mapping = aes(x = disp, y = mpg)
    )
```
